# Catppuccin Mocha Theme for Alacritty
# https://github.com/catppuccin/alacritty

[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'
dim_foreground = '#cdd6f4'
bright_foreground = '#cdd6f4'

[colors.normal]
black = '#45475a'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#94e2d5'
white = '#bac2de'

[colors.bright]
black = '#585b70'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#94e2d5'
white = '#a6adc8'

[colors.selection]
text = '#1e1e2e'
background = '#f5e0dc'

[colors.cursor]
text = '#1e1e2e'
cursor = '#f5e0dc'

[colors.search]
matches = { foreground = '#1e1e2e', background = '#f5e0dc' }
focused_match = { foreground = '#1e1e2e', background = '#a6e3a1' } 
